from __future__ import annotations

from collections import OrderedDict


def _terms(text: str) -> list[str]:
    return [part.strip() for part in text.split("|") if part.strip()]


QUERY_GROUPS: OrderedDict[str, list[str]] = OrderedDict({
    "fresh_fruit": _terms("""
apple|gala apple|fuji apple|honeycrisp apple|granny smith apple|pink lady apple|cosmic crisp apple|red delicious apple|golden delicious apple|ambrosia apple|envy apple|jazz apple|braeburn apple|mcintosh apple|green apple|organic apple|apple slices|pear|bartlett pear|anjou pear|bosc pear|asian pear|red pear|prickly pear|banana|organic banana|plantain|baby banana|red banana|orange|navel orange|cara cara orange|blood orange|mandarin|clementine|tangerine|tangelo|grapefruit|ruby red grapefruit|pomelo|lemon|meyer lemon|lime|key lime|peach|white peach|yellow peach|nectarine|white nectarine|plum|red plum|black plum|apricot|cherry|rainier cherry|dark sweet cherry|strawberry|blueberry|raspberry|blackberry|cranberry|gooseberry|currant|grape|red grapes|green grapes|black grapes|cotton candy grapes|watermelon|mini watermelon|cantaloupe|honeydew|melon|pineapple|mango|ataulfo mango|papaya|kiwi|gold kiwi|dragon fruit|passion fruit|pomegranate|avocado|hass avocado|coconut|fig|fresh dates|medjool dates|guava|lychee|persimmon|star fruit|jackfruit|rambutan|tamarind|quince|fruit cup|fruit tray|fresh cut fruit|frozen fruit|mixed berries|acai|pitaya|dried fruit|raisins|prunes|dried apricots|dried mango|freeze dried fruit
"""),
    "fresh_vegetables": _terms("""
potato|russet potato|red potato|gold potato|fingerling potato|sweet potato|yam|onion|yellow onion|white onion|red onion|sweet onion|pearl onion|shallot|garlic|peeled garlic|leek|scallion|green onion|chives|carrot|baby carrots|rainbow carrots|celery|celery root|broccoli|broccoli florets|broccolini|cauliflower|cauliflower florets|cabbage|green cabbage|red cabbage|savoy cabbage|napa cabbage|brussels sprouts|spinach|baby spinach|kale|curly kale|lacinato kale|lettuce|iceberg lettuce|romaine lettuce|butter lettuce|green leaf lettuce|red leaf lettuce|spring mix|arugula|collard greens|mustard greens|turnip greens|swiss chard|bok choy|baby bok choy|watercress|asparagus|green beans|wax beans|snap peas|snow peas|green peas|corn|corn on the cob|cucumber|english cucumber|mini cucumber|zucchini|yellow squash|summer squash|butternut squash|acorn squash|spaghetti squash|delicata squash|kabocha squash|pumpkin|eggplant|japanese eggplant|bell pepper|red bell pepper|green bell pepper|yellow bell pepper|orange bell pepper|mini sweet peppers|jalapeno|serrano pepper|poblano pepper|habanero pepper|anaheim pepper|shishito pepper|fresno pepper|tomato|roma tomato|beefsteak tomato|vine tomato|cherry tomato|grape tomato|heirloom tomato|tomatillo|mushroom|white mushrooms|cremini mushrooms|portobello mushroom|shiitake mushroom|oyster mushroom|maitake mushroom|enoki mushroom|okra|radish|daikon radish|turnip|rutabaga|beet|golden beet|parsnip|artichoke|fennel|jicama|kohlrabi|cassava|yucca|taro root|ginger root|turmeric root|bean sprouts|alfalfa sprouts|bamboo shoots|hearts of palm|nopales|cactus paddles|vegetable tray|spiralized vegetables|riced cauliflower|coleslaw mix|salad kit|fresh salsa|fresh guacamole
"""),
    "fresh_herbs": _terms("""
fresh basil|fresh cilantro|fresh parsley|fresh italian parsley|fresh dill|fresh mint|fresh rosemary|fresh thyme|fresh sage|fresh oregano|fresh tarragon|fresh marjoram|fresh chervil|fresh lemongrass|fresh bay leaves|fresh lavender|microgreens|edible flowers|poultry herb blend|seafood herb blend
"""),
    "meat_poultry": _terms("""
chicken breast|boneless chicken breast|bone in chicken breast|thin sliced chicken breast|chicken thighs|boneless chicken thighs|bone in chicken thighs|chicken wings|whole chicken wings|party wings|chicken drumsticks|chicken leg quarters|whole chicken|cornish hen|ground chicken|chicken tenderloins|chicken cutlets|rotisserie chicken|chicken sausage|turkey breast|turkey tenderloin|turkey thighs|turkey wings|turkey drumsticks|whole turkey|ground turkey|turkey sausage|turkey bacon|duck breast|whole duck|duck legs|goose|quail|beef ground|ground beef 80 20|ground beef 85 15|ground beef 90 10|ground sirloin|ground chuck|beef patties|beef ribeye steak|beef strip steak|new york strip steak|beef sirloin steak|top sirloin steak|filet mignon|beef tenderloin|beef flank steak|beef skirt steak|beef hanger steak|beef flat iron steak|beef chuck steak|beef round steak|beef cube steak|beef tri tip|beef brisket|beef chuck roast|beef pot roast|beef rump roast|beef eye round roast|beef bottom round roast|beef short ribs|beef back ribs|beef stew meat|beef shank|beef oxtail|beef liver|beef tongue|beef heart|beef tripe|corned beef|roast beef|pastrami|pork chops|boneless pork chops|bone in pork chops|pork tenderloin|pork loin|pork shoulder|pork butt|pork picnic roast|pork ribs|baby back ribs|spare ribs|country style ribs|pork belly|ground pork|pork sausage|italian sausage|breakfast sausage|bratwurst|kielbasa|andouille sausage|chorizo|pork bacon|thick cut bacon|canadian bacon|ham steak|spiral ham|whole ham|prosciutto|pancetta|salami|pepperoni|lamb chops|lamb loin chops|lamb shoulder chops|leg of lamb|lamb shank|ground lamb|lamb rack|veal chops|veal cutlets|ground veal|bison ground|bison steak|venison|rabbit meat|goat meat|meatballs|fajita meat|carne asada|barbacoa meat|gyro meat|hot dogs|beef hot dogs|turkey hot dogs|deli turkey|deli ham|deli chicken|deli roast beef|deli salami|deli pepperoni|lunch meat
"""),
    "seafood": _terms("""
salmon|atlantic salmon|sockeye salmon|coho salmon|smoked salmon|salmon fillet|salmon portions|tuna steak|ahi tuna|canned tuna|tilapia|cod|pacific cod|haddock|halibut|mahi mahi|swordfish|trout|rainbow trout|catfish|swai|pollock|flounder|sole fish|sea bass|branzino|red snapper|grouper|mackerel|sardines|anchovies|herring|whitefish|perch|walleye|orange roughy|monkfish|barramundi|arctic char|eel|shrimp|raw shrimp|cooked shrimp|jumbo shrimp|cocktail shrimp|breaded shrimp|prawns|lobster|lobster tail|crab legs|snow crab|king crab|blue crab|crab meat|imitation crab|crawfish|crayfish|scallops|sea scallops|bay scallops|oysters|mussels|clams|calamari|squid|octopus|seafood mix|fish sticks|breaded fish|fish fillets|ceviche|poke|sushi|seaweed salad
"""),
    "eggs_dairy": _terms("""
eggs|large eggs|extra large eggs|jumbo eggs|brown eggs|white eggs|organic eggs|cage free eggs|free range eggs|pasture raised eggs|egg whites|liquid eggs|hard boiled eggs|quail eggs|whole milk|2 percent milk|1 percent milk|skim milk|lactose free milk|organic milk|ultra filtered milk|goat milk|shelf stable milk|evaporated milk|condensed milk|powdered milk|buttermilk|chocolate milk|strawberry milk|almond milk|oat milk|soy milk|coconut milk beverage|cashew milk|rice milk|pea milk|half and half|heavy cream|heavy whipping cream|light cream|coffee creamer|sour cream|creme fraiche|yogurt|greek yogurt|plain yogurt|vanilla yogurt|fruit yogurt|skyr|kefir|cottage cheese|ricotta cheese|cream cheese|mascarpone|butter|salted butter|unsalted butter|irish butter|clarified butter|ghee|margarine|whipped butter
"""),
    "cheese": _terms("""
cheddar cheese|mild cheddar|medium cheddar|sharp cheddar|extra sharp cheddar|white cheddar|colby cheese|colby jack|monterey jack|pepper jack|mozzarella cheese|fresh mozzarella|low moisture mozzarella|provolone cheese|swiss cheese|baby swiss|gruyere cheese|emmental cheese|gouda cheese|smoked gouda|edam cheese|havarti cheese|muenster cheese|fontina cheese|asiago cheese|parmesan cheese|parmigiano reggiano|pecorino romano|romano cheese|grana padano|feta cheese|goat cheese|chevre|blue cheese|gorgonzola|roquefort|brie cheese|camembert cheese|manchego cheese|queso fresco|queso blanco|cotija cheese|oaxaca cheese|asadero cheese|quesadilla cheese|paneer|halloumi|burrata|neufchatel cheese|limburger cheese|stilton cheese|raclette cheese|comte cheese|jarlsberg cheese|emmentaler|farmer cheese|string cheese|cheese slices|shredded cheese|cheese cubes|cheese curds|cheese spread|vegan cheese
"""),
    "grains_rice_pasta": _terms("""
white rice|long grain rice|medium grain rice|short grain rice|jasmine rice|basmati rice|brown rice|wild rice|arborio rice|sushi rice|sticky rice|black rice|red rice|yellow rice|parboiled rice|instant rice|rice blend|quinoa|white quinoa|red quinoa|tricolor quinoa|barley|pearl barley|farro|bulgur|couscous|pearl couscous|millet|sorghum|buckwheat|amaranth|teff|polenta|cornmeal|grits|oats|rolled oats|quick oats|steel cut oats|instant oatmeal|cream of wheat|cream of rice|wheat berries|rye berries|spelt|freekeh|pasta|spaghetti|thin spaghetti|angel hair pasta|linguine|fettuccine|tagliatelle|pappardelle|bucatini|penne|rigatoni|ziti|rotini|fusilli|farfalle|elbow macaroni|shell pasta|orecchiette|orzo|lasagna noodles|manicotti|cannelloni|gnocchi|tortellini|ravioli|egg noodles|ramen noodles|udon noodles|soba noodles|rice noodles|vermicelli|glass noodles|lo mein noodles|chow mein noodles|shirataki noodles|gluten free pasta|chickpea pasta|lentil pasta|protein pasta|macaroni and cheese
"""),
    "bread_bakery": _terms("""
white bread|wheat bread|whole grain bread|multigrain bread|sourdough bread|rye bread|pumpernickel bread|brioche bread|challah bread|french bread|italian bread|baguette|ciabatta|focaccia|texas toast|sandwich thins|english muffins|bagels|plain bagels|everything bagels|hamburger buns|hot dog buns|slider buns|dinner rolls|hawaiian rolls|croissants|biscuits|cornbread|naan|pita bread|flatbread|lavash|tortillas|flour tortillas|corn tortillas|whole wheat tortillas|low carb tortillas|tostadas|taco shells|pizza crust|pizza dough|pie crust|crescent rolls|cinnamon rolls|donuts|muffins|scones|danish pastry|coffee cake|pound cake|cupcakes|cookies bakery|brownies bakery|fresh cake|cheesecake|tres leches cake|pan dulce|conchas|bolillo rolls
"""),
    "beans_legumes_nuts": _terms("""
black beans|pinto beans|kidney beans|red beans|navy beans|great northern beans|cannellini beans|lima beans|butter beans|garbanzo beans|chickpeas|black eyed peas|split peas|green lentils|brown lentils|red lentils|black lentils|french lentils|refried beans|baked beans|bean soup|edamame|soybeans|mung beans|adzuki beans|fava beans|lupini beans|peanuts|almonds|cashews|walnuts|pecans|pistachios|hazelnuts|macadamia nuts|brazil nuts|pine nuts|chestnuts|mixed nuts|sunflower seeds|pumpkin seeds|pepitas|sesame seeds|chia seeds|flax seeds|hemp seeds|poppy seeds|nut butter|peanut butter|almond butter|cashew butter|sunflower butter|tahini
"""),
    "oils_vinegars": _terms("""
olive oil|extra virgin olive oil|light olive oil|avocado oil|canola oil|vegetable oil|corn oil|peanut oil|sunflower oil|safflower oil|grapeseed oil|sesame oil|toasted sesame oil|coconut oil|mct oil|walnut oil|flaxseed oil|rice bran oil|soybean oil|truffle oil|chili oil|cooking spray|olive oil spray|butter spray|white vinegar|distilled vinegar|apple cider vinegar|red wine vinegar|white wine vinegar|balsamic vinegar|rice vinegar|seasoned rice vinegar|sherry vinegar|champagne vinegar|malt vinegar|black vinegar|coconut vinegar|vinegar glaze
"""),
    "spices_seasonings": _terms("""
salt|table salt|kosher salt|sea salt|pink himalayan salt|smoked salt|black pepper|white pepper|peppercorns|cayenne pepper|paprika|smoked paprika|sweet paprika|chili powder|ancho chili powder|chipotle powder|red pepper flakes|crushed red pepper|garlic powder|onion powder|celery salt|seasoned salt|lemon pepper|cumin|ground cumin|coriander seed|ground coriander|turmeric|ground ginger|cinnamon|cinnamon sticks|nutmeg|mace spice|cloves|allspice|cardamom|star anise|anise seed|fennel seed|mustard seed|ground mustard|fenugreek|saffron|sumac|zaatar|caraway seed|dill seed|celery seed|poppy seed|sesame seed|bay leaves|dried basil|dried oregano|dried thyme|dried rosemary|dried sage|dried parsley|dried dill|tarragon|marjoram|chervil|herbes de provence|italian seasoning|poultry seasoning|seafood seasoning|cajun seasoning|creole seasoning|taco seasoning|fajita seasoning|chili seasoning|steak seasoning|burger seasoning|bbq rub|pork rub|chicken rub|fish seasoning|adobo seasoning|sazon seasoning|jerk seasoning|curry powder|garam masala|tandoori seasoning|ras el hanout|berbere seasoning|five spice powder|everything bagel seasoning|ranch seasoning|onion soup mix|bouillon cubes|chicken bouillon|beef bouillon|vegetable bouillon|msg seasoning|nutritional yeast
"""),
    "sauces_condiments": _terms("""
ketchup|mustard|yellow mustard|dijon mustard|whole grain mustard|spicy brown mustard|mayonnaise|light mayonnaise|miracle whip|relish|pickle relish|barbecue sauce|hot sauce|buffalo sauce|wing sauce|sriracha|chili garlic sauce|sambal oelek|gochujang|harissa|taco sauce|enchilada sauce|salsa|salsa verde|pico de gallo|guacamole|queso dip|soy sauce|low sodium soy sauce|tamari|coconut aminos|fish sauce|oyster sauce|hoisin sauce|teriyaki sauce|ponzu sauce|sweet chili sauce|duck sauce|plum sauce|black bean sauce|stir fry sauce|tahini sauce|tzatziki|hummus|pesto|alfredo sauce|marinara sauce|pasta sauce|tomato sauce|pizza sauce|vodka sauce|bolognese sauce|curry sauce|gravy|brown gravy|country gravy|cranberry sauce|applesauce|horseradish|wasabi|cocktail sauce|tartar sauce|steak sauce|worcestershire sauce|liquid smoke|browning sauce|mint sauce|chimichurri|salad dressing|ranch dressing|italian dressing|caesar dressing|blue cheese dressing|vinaigrette|balsamic dressing|thousand island dressing|honey mustard dressing|sesame dressing|oil and vinegar dressing
"""),
    "canned_jarred_pantry": _terms("""
canned tomatoes|diced tomatoes|crushed tomatoes|whole peeled tomatoes|tomato paste|tomato puree|canned corn|canned green beans|canned peas|canned carrots|canned mixed vegetables|canned mushrooms|canned potatoes|canned spinach|canned beets|canned pumpkin|canned sweet potato|canned artichokes|canned asparagus|canned jalapenos|green chiles|chipotle peppers|roasted red peppers|sun dried tomatoes|olives|black olives|green olives|kalamata olives|pickles|dill pickles|bread and butter pickles|pickled jalapenos|pickled onions|pickled beets|sauerkraut|kimchi|canned chicken|canned beef|canned ham|spam|corned beef hash|canned salmon|canned sardines|canned anchovies|canned clams|canned crab|canned oysters|canned soup|chicken noodle soup|tomato soup|cream of mushroom soup|cream of chicken soup|vegetable soup|beef soup|chili canned|broth|chicken broth|beef broth|vegetable broth|bone broth|stock|ramen cups|instant noodles|instant mashed potatoes|stuffing mix|rice mix|pasta side|boxed meals|meal kits|taco kit|curry paste|red curry paste|green curry paste|miso paste|mole sauce|coconut cream|canned coconut milk
"""),
    "baking_flours": _terms("""
all purpose flour|bread flour|cake flour|pastry flour|whole wheat flour|self rising flour|00 flour|semolina flour|rye flour|spelt flour|buckwheat flour|rice flour|brown rice flour|oat flour|corn flour|masa harina|almond flour|coconut flour|chickpea flour|cassava flour|tapioca flour|potato starch|cornstarch|arrowroot powder|vital wheat gluten|baking powder|baking soda|cream of tartar|active dry yeast|instant yeast|sourdough starter|gelatin|pectin|xanthan gum|guar gum|cocoa powder|dutch cocoa|cacao powder|chocolate chips|dark chocolate chips|white chocolate chips|butterscotch chips|peanut butter chips|baking chocolate|candy melts|sprinkles|food coloring|vanilla extract|vanilla bean paste|almond extract|lemon extract|peppermint extract|maple extract|coconut extract|rum extract|orange extract|rose water|orange blossom water|molasses|corn syrup|golden syrup|maple syrup|agave nectar|honey|granulated sugar|brown sugar|powdered sugar|cane sugar|turbinado sugar|demerara sugar|coconut sugar|date sugar|stevia|monk fruit sweetener|erythritol|splenda|sweetened condensed milk|pie filling|cherry pie filling|apple pie filling|marshmallows|shredded coconut|candied fruit|candied ginger
"""),
    "breakfast": _terms("""
breakfast cereal|corn flakes|bran flakes|rice cereal|oat cereal|granola|muesli|granola bars|protein bars|breakfast bars|pancake mix|waffle mix|maple pancake syrup|frozen waffles|frozen pancakes|french toast sticks|toaster pastries|pop tarts|breakfast biscuits|breakfast sandwiches|breakfast burritos|hash browns|tater tots|frozen breakfast|overnight oats|chia pudding
"""),
    "snacks": _terms("""
potato chips|tortilla chips|corn chips|pita chips|pretzels|popcorn|microwave popcorn|cheese puffs|cheese crackers|crackers|saltine crackers|graham crackers|rice cakes|snack mix|trail mix|beef jerky|turkey jerky|meat sticks|fruit snacks|fruit leather|applesauce pouches|pudding cups|gelatin cups|yogurt snacks|cookies|chocolate cookies|sandwich cookies|wafer cookies|shortbread cookies|oatmeal cookies|peanut butter cookies|chocolate candy|gummy candy|hard candy|caramels|mints|gum|protein snacks|seaweed snacks|roasted chickpeas|pork rinds|plantain chips|veggie chips|granola bites|energy bites|snack nuts|chocolate covered nuts|dried seaweed
"""),
    "beverages": _terms("""
bottled water|spring water|purified water|distilled water|mineral water|sparkling water|flavored water|electrolyte water|coconut water|tonic water|club soda|seltzer|cola|diet cola|root beer|ginger ale|lemon lime soda|orange soda|grape soda|cream soda|craft soda|energy drink|sports drink|electrolyte drink|protein shake|meal replacement shake|coffee beans|ground coffee|instant coffee|coffee pods|cold brew coffee|iced coffee|espresso|decaf coffee|black tea|green tea|herbal tea|chai tea|matcha|tea bags|iced tea|sweet tea|lemonade|limeade|orange juice|apple juice|grape juice|cranberry juice|pineapple juice|grapefruit juice|tomato juice|vegetable juice|fruit punch|juice boxes|nectar drink|smoothie|kombucha|probiotic drink|hot chocolate|cocoa mix|horchata|agua fresca|non alcoholic beer|mocktail mixer|cocktail mixer|margarita mix|bloody mary mix|grenadine|simple syrup|flavored syrup
"""),
    "frozen_food": _terms("""
frozen vegetables|frozen broccoli|frozen spinach|frozen peas|frozen corn|frozen mixed vegetables|frozen potatoes|frozen french fries|frozen onion rings|frozen fruit|frozen berries|frozen mango|frozen pineapple|frozen chicken|frozen beef|frozen fish|frozen shrimp|frozen meatballs|frozen pizza|frozen pasta|frozen lasagna|frozen burritos|frozen tacos|frozen enchiladas|frozen dumplings|frozen potstickers|frozen egg rolls|frozen spring rolls|frozen fried rice|frozen meals|frozen dinners|frozen soup|frozen bread dough|frozen pie crust|frozen biscuits|ice cream|vanilla ice cream|chocolate ice cream|strawberry ice cream|gelato|sorbet|frozen yogurt|ice cream bars|ice cream sandwiches|popsicles|frozen dessert|frozen cheesecake
"""),
    "international_food": _terms("""
mexican food|latin food|tex mex|asian food|chinese food|japanese food|korean food|thai food|vietnamese food|indian food|middle eastern food|mediterranean food|italian food|caribbean food|african food|filipino food|hawaiian food|kosher food|halal food|masa|hominy|pozole|tamales|taco meat|tortilla chips|queso|mole|sofrito|recaito|achiote paste|annatto|adobo sauce|sazon|jerk sauce|curry paste|curry sauce|naan|papadum|basmati rice|paneer|dal|chutney|mango chutney|kimchi|gochujang|doenjang|seaweed sheets|nori|sushi ginger|rice paper|spring roll wrappers|wonton wrappers|dumpling wrappers|tofu|silken tofu|firm tofu|tempeh|seitan|miso|dashi|furikake|bonito flakes|mirin|rice cooking wine|sesame paste|tahini|falafel mix|couscous|harissa|hummus|pita|feta|gyro|pierogi|gnocchi|polenta|pesto|passata|capers|artichoke hearts
"""),
    "plant_based_specialty": _terms("""
vegan meat|plant based meat|meatless burgers|veggie burgers|vegan chicken|vegan sausage|vegan bacon|vegan deli meat|tofu|tempeh|seitan|jackfruit meat|vegan cheese|dairy free yogurt|dairy free ice cream|gluten free bread|gluten free flour|gluten free snacks|keto food|low carb food|paleo food|organic food|sugar free food|low sodium food|protein powder|collagen powder|greens powder|meal replacement|nutrition shake
"""),
    "prepared_deli": _terms("""
prepared salad|caesar salad|garden salad|cobb salad|chef salad|pasta salad|potato salad|macaroni salad|coleslaw|chicken salad|tuna salad|egg salad|deli sandwich|wrap sandwich|sub sandwich|ready meals|prepared meals|meal kit|rotisserie chicken|fried chicken|chicken tenders|chicken wings prepared|mashed potatoes prepared|macaroni and cheese prepared|sushi tray|party tray|cheese tray|meat tray|charcuterie|fresh soup|pizza deli|take and bake pizza
"""),
})


def build_round_robin_queries() -> list[tuple[str, str]]:
    """Interleave aisles so early stopping still yields broad coverage."""
    groups = [(group, list(dict.fromkeys(terms))) for group, terms in QUERY_GROUPS.items()]
    output: list[tuple[str, str]] = []
    max_len = max(len(terms) for _, terms in groups)
    seen: set[str] = set()
    for index in range(max_len):
        for group, terms in groups:
            if index >= len(terms):
                continue
            query = " ".join(terms[index].split()).strip().lower()
            if not query or query in seen:
                continue
            seen.add(query)
            output.append((group, query))
    return output


QUERIES = build_round_robin_queries()
